language: python

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      name: "Linux"
      python: 3.7
    - os: osx
      language: minimal
install:
  - pip3 install -r requirements.txt
  - pip3 install pytest==5.0.1
script: pytest
