language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.1 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell       # 'language: python' is an error on Travis CI macOS
install:
    - pip3 install -r requirements.txt
    - pip3 install pytest==5.0.1
script: pytest
