language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial          # required for Python >= 3.7
install:
    - pip3 install -r requirements.txt
    - pip3 install pytest
script: pytest
